import type {
  ReadingsFeatureCollection,
  StationHistoryResponse,
} from "../../lib/ui/types";

export const MOCK_READINGS: ReadingsFeatureCollection = {
  type: "FeatureCollection",
  bbox: [-168, 6, -52, 72],
  features: [
    {
      type: "Feature",
      id: "test-chicago",
      geometry: { type: "Point", coordinates: [-87.6298, 41.8781] },
      properties: {
        stationId: "test-chicago",
        stationName: "Chicago — Com Ed",
        countryCode: "US",
        stateCode: "IL",
        reportingAreas: ["Chicago"],
        observedAt: "2026-07-16T22:00:00.000Z",
        freshness: "fresh",
        pm25Aqi: 64,
        aqiCategory: "moderate",
        pm25UgM3: 17.2,
        projectedCigaretteEquivalentsPerDay: 0.7818,
        methodologyVersion: "berkeley-earth-22-v1",
        sourceAgency: "Illinois EPA",
        isPreliminary: true,
        dataMode: "demo",
      },
    },
    {
      type: "Feature",
      id: "test-los-angeles",
      geometry: { type: "Point", coordinates: [-118.2267, 34.0664] },
      properties: {
        stationId: "test-los-angeles",
        stationName: "Los Angeles — North Main",
        countryCode: "US",
        stateCode: "CA",
        reportingAreas: ["Los Angeles"],
        observedAt: "2026-07-16T22:00:00.000Z",
        freshness: "fresh",
        pm25Aqi: 158,
        aqiCategory: "unhealthy",
        pm25UgM3: 59.4,
        projectedCigaretteEquivalentsPerDay: 2.7,
        methodologyVersion: "berkeley-earth-22-v1",
        sourceAgency: "South Coast AQMD",
        isPreliminary: true,
        dataMode: "demo",
      },
    },
    {
      type: "Feature",
      id: "test-seattle",
      geometry: { type: "Point", coordinates: [-122.3086, 47.5682] },
      properties: {
        stationId: "test-seattle",
        stationName: "Seattle — Beacon Hill",
        countryCode: "US",
        stateCode: "WA",
        reportingAreas: ["Seattle–Bellevue–Kent Valley"],
        observedAt: "2026-07-16T21:00:00.000Z",
        freshness: "stale",
        pm25Aqi: 18,
        aqiCategory: "good",
        pm25UgM3: 4.4,
        projectedCigaretteEquivalentsPerDay: 0.2,
        methodologyVersion: "berkeley-earth-22-v1",
        sourceAgency: "Puget Sound Clean Air Agency",
        isPreliminary: true,
        dataMode: "demo",
      },
    },
  ],
  meta: {
    generatedAt: "2026-07-16T22:00:00.000Z",
    newestObservedAt: "2026-07-16T22:00:00.000Z",
    dataMode: "demo",
    featureCount: 3,
    truncated: false,
    freshWithinHours: 6,
    limit: 2_500,
    freshnessCounts: { fresh: 2, stale: 1, expired: 0 },
    sourceFile: null,
    fallbackReason: "Deterministic browser fixture",
    methodologyVersion: "berkeley-earth-22-v1",
  },
};

export const MOCK_HISTORY: StationHistoryResponse = {
  station: {
    stationId: "test-chicago",
    stationName: "Chicago — Com Ed",
    latitude: 41.8781,
    longitude: -87.6298,
    countryCode: "US",
    stateCode: "IL",
    reportingAreas: ["Chicago"],
    sourceAgency: "Illinois EPA",
  },
  observations: [],
  series: Array.from({ length: 24 }, (_, index) => ({
    observedAt: new Date(Date.UTC(2026, 6, 15, 23 + index)).toISOString(),
    pm25UgM3: index < 4 ? null : 12 + (index % 7),
    pm25Aqi: index < 4 ? null : 52 + index,
    aqiCategory: index < 4 ? null : "moderate" as const,
    projectedCigaretteEquivalentsPerDay:
      index < 4 ? null : (12 + (index % 7)) / 22,
    sourceAgency: index < 4 ? null : "Illinois EPA",
    isPreliminary: index >= 4,
    isGap: index < 4,
  })),
  summary: {
    cigaretteEquivalents: 0.56,
    capturedHours: 20,
    expectedHours: 24,
    completenessPercent: 83.333,
    distinctHourlyReadings: 20,
    longestMissingGapHours: 4,
    isComplete: false,
    windowStart: "2026-07-15T23:00:00.000Z",
    windowEnd: "2026-07-16T23:00:00.000Z",
    methodologyVersion: "berkeley-earth-22-v1",
  },
  meta: {
    dataMode: "database",
    persistentHistoryAvailable: true,
    requestedHours: 24,
  },
};

export const MINIMAL_MAP_STYLE = {
  version: 8 as const,
  name: "Air Equivalent browser-test field map",
  glyphs: "https://fonts.openmaptiles.org/{fontstack}/{range}.pbf",
  sources: {},
  layers: [
    {
      id: "paper",
      type: "background" as const,
      paint: { "background-color": "#dfe6d8" },
    },
  ],
};
